In [22]:
from dgsp.estimators import ParticleFilter

In [23]:
filter = ParticleFilter(dt=1e-3, n_particles=1000)

In [24]:
filter.particles.shape

(1000, 4)

In [25]:
filter.weights.shape

(1000,)

In [26]:
import numpy as np

In [27]:
np.average(filter.particles, weights=filter.weights, axis=0)

array([0., 0., 0., 0.])

In [28]:
for i in range(1000):
    filter.predict()
    if i % 100 == 0:
        filter.update(np.zeros(2))

In [29]:
filter.state

[array([0., 0., 0., 0.]),
 array([ 2.99268489e-03,  8.04658683e-06, -2.00966429e-04,  1.30183899e-04]),
 array([ 5.99004957e-03,  2.37423023e-07, -3.36380925e-04,  3.41107783e-04]),
 array([ 8.97469809e-03,  9.94409553e-06, -1.64684359e-04,  3.93108618e-04]),
 array([ 1.19514429e-02,  1.58110204e-05, -4.37182001e-04,  2.46009821e-04]),
 array([ 1.49557065e-02,  5.06425136e-06, -6.97966798e-04,  2.65632923e-04]),
 array([ 1.79266328e-02, -1.57772871e-06, -6.60996064e-04,  1.44448707e-04]),
 array([ 2.09172704e-02,  2.04394350e-05, -7.42303275e-04,  1.62192188e-04]),
 array([ 2.39165203e-02,  2.16734149e-05, -7.85628858e-04,  3.45861921e-04]),
 array([ 2.69216991e-02,  1.62063434e-05, -7.53254986e-04,  4.44801113e-04]),
 array([ 2.99279302e-02,  1.39113335e-05, -4.27126992e-04,  1.35300279e-04]),
 array([ 3.29204132e-02,  1.91506487e-05, -6.46338497e-04,  5.25666075e-04]),
 array([ 3.59298877e-02,  1.04834400e-05, -1.01932731e-03,  6.23241570e-04]),
 array([ 3.89294932e-02,  2.13974650e-

In [30]:
filter.k

[array([[3.e-07, 0.e+00, 0.e+00, 0.e+00],
        [0.e+00, 3.e-07, 0.e+00, 0.e+00],
        [0.e+00, 0.e+00, 3.e-05, 0.e+00],
        [0.e+00, 0.e+00, 0.e+00, 3.e-05]]),
 array([[0.00055828, 0.        , 0.        , 0.        ],
        [0.        , 0.00053193, 0.        , 0.        ],
        [0.        , 0.        , 0.0055545 , 0.        ],
        [0.        , 0.        , 0.        , 0.00548595]]),
 array([[0.00075903, 0.        , 0.        , 0.        ],
        [0.        , 0.00076451, 0.        , 0.        ],
        [0.        , 0.        , 0.00773471, 0.        ],
        [0.        , 0.        , 0.        , 0.00796563]]),
 array([[0.00091255, 0.        , 0.        , 0.        ],
        [0.        , 0.00093221, 0.        , 0.        ],
        [0.        , 0.        , 0.00937329, 0.        ],
        [0.        , 0.        , 0.        , 0.0096301 ]]),
 array([[0.0010776 , 0.        , 0.        , 0.        ],
        [0.        , 0.00110284, 0.        , 0.        ],
        [0. 

In [31]:
a = np.ones(2)
b = np.zeros(2)

In [32]:
(a - b) ** 2

array([1., 1.])

In [33]:
from scipy.stats import multivariate_normal as norm

In [34]:
norm(np.linalg.norm(a-b) * np.ones(2), cov=np.eye(2)).pdf(0)

np.float64(0.021539279301848624)